app: kinnie

mysql:
    host: localhost
    port: 3306
    root:
        user: root
        password: password
    app:
        user: user
        password: password

spotify:
    url: https://accounts.spotify.com/
    client_id: id
    client_secret: secret

client: http://localhost:3000/
server: http://localhost:5000/